
services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 2546
      MYSQL_DATABASE: dbecommerce
      MYSQL_USER: usernorm
      MYSQL_PASSWORD: 4685
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - database
    environment:
      - ASPNETCORE_URLS=http://+:80  # Escuchar en todas las interfaces
      - ConnectionStrings__DefaultConnection=Server=database;Port=3306;Database=dbecommerce;User=usernorm;Password=4685;

volumes:
  db_data:
